/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posibleexamen;

import java.awt.Image;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author edcarlitosxd
 */
public class Frame extends javax.swing.JFrame {
    int rndAzul,rndMorado,rndNaranja,rndPersona,rndRojo,rndRosa,rndVerde;
    ImageIcon imgAzul, imgMorado, imgNaranja, imgPersona, imgRojo,imgRosa,imgVerde;
    public Timer tiempo;
    boolean right,left;

    public ActionListener al = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {

            mover(lblAzul,rndAzul);
            mover(lblMorado,rndMorado);
            mover(lblNaranja,rndNaranja);
            mover(lblPersona,rndPersona);
            mover(lblRojo,rndRojo);
            mover(lblRosa,rndRosa);
            mover(lblVerde,rndVerde);

            
          
        }

    };
    

    Image azul = new ImageIcon(getClass().getResource("examen/azul.jpeg")).getImage();
    Image morado = new ImageIcon(getClass().getResource("examen/morado.jpeg")).getImage();
    Image naranja = new ImageIcon(getClass().getResource("examen/naranja.jpeg")).getImage();
    Image persona = new ImageIcon(getClass().getResource("examen/persona.jpeg")).getImage();
    Image rojo = new ImageIcon(getClass().getResource("examen/rojo.jpeg")).getImage();
    Image rosa = new ImageIcon(getClass().getResource("examen/rosa.jpeg")).getImage();
    Image verde = new ImageIcon(getClass().getResource("examen/verde.jpeg")).getImage();
    
    public Frame() {
        initComponents();
        
        tiempo = new Timer(100, al);
        
        imgAzul = new ImageIcon(azul.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgMorado = new ImageIcon(morado.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgNaranja = new ImageIcon(naranja.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgPersona = new ImageIcon(persona.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgRojo = new ImageIcon(rojo.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgRosa = new ImageIcon(rosa.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        imgVerde = new ImageIcon(verde.getScaledInstance(lblAzul.getWidth(), lblAzul.getHeight(), Image.SCALE_SMOOTH));
        
        lblAzul.setIcon((imgAzul));
        lblMorado.setIcon(imgMorado);
        lblNaranja.setIcon(imgNaranja);
        lblPersona.setIcon(imgPersona);
        lblRojo.setIcon(imgRojo);
        lblRosa.setIcon(imgRosa);
        lblVerde.setIcon(imgVerde);
        
        
    }

    private void mover(JLabel lbl, int rnd){
       
      if (right == true) {
            lbl.setLocation(lbl.getLocation().x + rnd, lbl.getLocation().y);
            if (lbl.getLocation().x > 650) {
                left = true;
                right = false;
                tiempo.stop();
                
                
               
            }
        } else if (left == true) {
            lbl.setLocation(lbl.getLocation().x - rnd, lbl.getLocation().y);
            if (lbl.getLocation().x <0) {
                   
                           
            }
        }
        
      
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        lblAzul = new javax.swing.JLabel();
        lblMorado = new javax.swing.JLabel();
        lblNaranja = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        lblRojo = new javax.swing.JLabel();
        lblRosa = new javax.swing.JLabel();
        lblVerde = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("Iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });

        lblAzul.setText("Azul");

        lblMorado.setText("Morado");

        lblNaranja.setText("Naranaja");

        lblPersona.setText("Persona");

        lblRojo.setText("Rojo");

        lblRosa.setText("Rosa");

        lblVerde.setText("Verde");

        lblGanador.setText("GANADOR :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMorado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMorado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        Random num = new Random();
        
        rndAzul = num.nextInt(20)+1;
        rndMorado = num.nextInt(20)+1;
        rndNaranja = num.nextInt(20)+1;
        rndPersona = num.nextInt(20)+1;
        rndRojo= num.nextInt(20)+1;
        rndRosa = num.nextInt(20)+1;
        rndVerde = num.nextInt(20)+1;
        
        System.out.println("Numero "+rndAzul);
        System.out.println("Numero "+rndMorado);
        System.out.println("Numero "+rndNaranja);
        System.out.println("Numero "+rndPersona);
        System.out.println("Numero "+rndRojo);
        System.out.println("Numero "+rndRosa);
        System.out.println("Numero "+rndVerde);
        
        
        right=true;
    
        tiempo.start();
        
        
    }//GEN-LAST:event_btnIniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    /* Numeros aleatorios con ARRAY
      reiniciar();
        contador =0;
        
        Random rdn = new Random();
        for (int i = 0; i <= 4; i++) {

            bomba[i] = rdn.nextInt(25)+1;
            System.out.println("A:" + bomba[i]);
            for (int atras = i - 1; atras >= 0; atras--) {
                if (bomba[i] == bomba[atras]) {
                    i--;
                }
            } //FOR
        }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblMorado;
    private javax.swing.JLabel lblNaranja;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblRosa;
    private javax.swing.JLabel lblVerde;
    // End of variables declaration//GEN-END:variables
}
